"use client";

import CarCard from "./CarCard";

const cars = [
    {
        category: "Sedan Car",
        name: "AC Swift Dzire",
        image: "/images/WhyChooseUs.png",
        passengers: 4,
        luggage: 4,
        ac: true,
        kms: "120 kms / 12 hours",
        rentalPrice: "₹2,500.00",
        nightDeliveryCharge: 200,
        discountedPrice: "₹2,475.00",
        gst: "134.00",
        totalPrice: "₹2,834.00",
        specialPrice: "₹2,809.00",
        extraKm: "₹13 per Km",
        extraHour: "₹150 per Hour",
    },
    {
        category: "Sedan Car",
        name: "AC Honda Amaze",
        image: "/images/honda-amaze.png",
        passengers: 4,
        luggage: 4,
        ac: true,
        kms: "120 kms / 12 hours",
        rentalPrice: "₹2,574.00",
        nightDeliveryCharge: 250,
        discountedPrice: "₹2,574.00",
        gst: "₹141.00",
        totalPrice: "₹2,965.00",
        specialPrice: "₹2,965.00",
        extraKm: "₹13 per Km",
        extraHour: "₹150 per Hour",
    },
    {
        category: "SUV Car",
        name: "AC Toyota Innova",
        image: "/images/toyota-innova.png",
        passengers: 7,
        luggage: 7,
        ac: true,
        kms: "120 kms / 12 hours",
        rentalPrice: "₹3,564.00",
        nightDeliveryCharge: 200,
        discountedPrice: "₹3,564.00",
        gst: "₹188.00",
        totalPrice: "₹3,952.00",
        specialPrice: "₹3,952.00",
        extraKm: "₹16 per Km",
        extraHour: "₹150 per Hour",
    },
    {
        category: "Luxury Car",
        name: "AC Honda City",
        image: "/images/honda-city.png",
        passengers: 4,
        luggage: 4,
        ac: true,
        kms: "120 kms / 12 hours",
        rentalPrice: "₹3,613.00",
        nightDeliveryCharge: 250,
        discountedPrice: "₹3,613.00",
        gst: "₹193.00",
        totalPrice: "₹4,056.00",
        specialPrice: "₹4,056.00",
        extraKm: "₹16 per Km",
        extraHour: "₹250 per Hour",
    },
    {
        category: "SUV Car",
        name: "AC Toyota Innova Crysta",
        image: "/images/toyota-innova-crysta.png",
        passengers: 7,
        luggage: 6,
        ac: true,
        kms: "120 kms / 12 hours",
        rentalPrice: "₹4,400.00",
        nightDeliveryCharge: 250,
        discountedPrice: "₹4,400.00",
        gst: "₹220.00",
        totalPrice: "₹4,628.00",
        specialPrice: "₹4,628.00",
        extraKm: "₹20 per Km",
        extraHour: "₹200 per Hour",
    },
    {
        category: "Luxury Car",
        name: "Hyundai Verna",
        image: "/images/hyundai-verna.png",
        passengers: 4,
        luggage: 4,
        ac: true,
        kms: "120 kms / 12 hours",
        rentalPrice: "₹3,200.00",
        nightDeliveryCharge: 250,
        discountedPrice: "₹3,150.00",
        gst: "₹175.00",
        totalPrice: "₹3,575.00",
        specialPrice: "₹3,550.00",
        extraKm: "₹14 per Km",
        extraHour: "₹200 per Hour",
    },
    {
        category: "SUV Car",
        name: "Maruti Suzuki Ertiga",
        image: "/images/ertiga.png",
        passengers: 6,
        luggage: 4,
        ac: true,
        kms: "120 kms / 12 hours",
        rentalPrice: "₹2,950.00",
        nightDeliveryCharge: 200,
        discountedPrice: "₹2,900.00",
        gst: "₹150.00",
        totalPrice: "₹3,250.00",
        specialPrice: "₹3,225.00",
        extraKm: "₹13 per Km",
        extraHour: "₹150 per Hour",
    },
    {
        category: "AC Winger",
        name: "AC 9 Seater Winger",
        image: "/images/winger-9.png",
        passengers: 9,
        luggage: 9,
        ac: true,
        kms: "120 kms / 12 hours",
        rentalPrice: "₹4,752.00",
        nightDeliveryCharge: 200,
        discountedPrice: "₹4,752.00",
        gst: "₹248.00",
        totalPrice: "₹5,200.00",
        specialPrice: "₹5,200.00",
        extraKm: "₹20 per Km",
        extraHour: "₹200 per Hour",
    },
    {
        category: "AC Force Traveller",
        name: "AC 13 Seater Traveller",
        image: "/images/traveller-13.png",
        passengers: 13,
        luggage: 13,
        ac: true,
        kms: "120 kms / 12 hours",
        rentalPrice: "₹6,090.00",
        nightDeliveryCharge: 200,
        discountedPrice: "₹6,090.00",
        gst: "₹307.00",
        totalPrice: "₹6,447.00",
        specialPrice: "₹6,447.00",
        extraKm: "₹25 per Km",
        extraHour: "₹200 per Hour",
    },
    {
        category: "AC Force Traveller",
        name: "AC 17 Seater Traveller",
        image: "/images/traveller-17.png",
        passengers: 17,
        luggage: 17,
        ac: true,
        kms: "120 kms / 12 hours",
        rentalPrice: "₹6,237.00",
        nightDeliveryCharge: 200,
        discountedPrice: "₹6,237.00",
        gst: "₹322.00",
        totalPrice: "₹6,759.00",
        specialPrice: "₹6,759.00",
        extraKm: "₹26 per Km",
        extraHour: "₹200 per Hour",
    },
    {
        category: "AC Force Traveller",
        name: "AC 25 Seater Traveller",
        image: "/images/traveller-25.png",
        passengers: 25,
        luggage: 25,
        ac: true,
        kms: "120 kms / 12 hours",
        rentalPrice: "₹8,615.00",
        nightDeliveryCharge: 200,
        discountedPrice: "₹8,615.00",
        gst: "₹431.00",
        totalPrice: "₹9,046.00",
        specialPrice: "₹9,046.00",
        extraKm: "₹28 per Km",
        extraHour: "₹350 per Hour",
    },
    {
        category: "Luxury Car",
        name: "AUDI A6",
        image: "/images/traveller-25.png",
        passengers: 4,
        luggage: 4,
        ac: true,
        kms: "120 kms / 12 hours",
        rentalPrice: "₹13,000.00",
        nightDeliveryCharge: 200,
        discountedPrice: "₹12,870.00",
        gst: "654.00",
        totalPrice: "₹13,854.00",
        specialPrice: "₹13,724.00",
        extraKm: "₹90 per Km",
        extraHour: "₹300 per Hour",
    },
    {
        category: "Luxury Car",
        name: "BMW 5 Series",
        image: "/images/bmw-5-series.png",
        passengers: 4,
        luggage: 4,
        ac: true,
        kms: "120 kms / 12 hours",
        rentalPrice: "₹14,751.00",
        nightDeliveryCharge: 500,
        discountedPrice: "₹14,751.00",
        gst: "₹763.00",
        totalPrice: "₹16,014.00",
        specialPrice: "₹16,014.00",
        extraKm: "₹100 per Km",
        extraHour: "₹900 per Hour",
    },
    {
        category: "Luxury Car",
        name: "Mercedes E250",
        image: "/images/mercedes-e250.png",
        passengers: 4,
        luggage: 4,
        ac: true,
        kms: "120 kms / 12 hours",
        rentalPrice: "₹14,850.00",
        nightDeliveryCharge: 200,
        discountedPrice: "₹14,850.00",
        gst: "₹753.00",
        totalPrice: "₹15,803.00",
        specialPrice: "₹15,803.00",
        extraKm: "₹95 per Km",
        extraHour: "₹400 per Hour",
    },
];

const CarsList = () => {
    return (
        <div className="w-full space-y-6">
            {cars.map((car, idx) => (
                <CarCard key={idx} {...car} />
            ))}
        </div>
    );
};

export default CarsList;
